<a href="https://colab.research.google.com/github/antonvandike/Simulacion-II/blob/main/Pruebas%20de%20aleatoriedad/prueba_independencia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Funcion para determinar la prueba de independencia de una lista de numeros

In [ ]:
def independencia(l):
  import numpy as np
  import math as mt
  import statistics as st

  n=len(N)
  s=[0]
  for x in range(1,n):
    if (N[x]-N[x-1])<0:
      s.append(-1)

    if (N[x]-N[x-1])>0:
      s.append(1)
  s=np.array(s)

  h=0;
  for x in range(1,n):
    if s[x-1] != s[x]:
      h=h+1

  s = np.reshape(s,(4,5));
  print('Los numeros categorizados son \n')
  print(s)
  print('\nEl numero de corridas es \n')
  print('h =',h)

  E = (2*n - 1)/3
  V = (16*n-29)/90

  Z = (h-E)/mt.sqrt(V)

  ND = st.NormalDist(0,1)

  Z_a = abs(round(ND.inv_cdf(0.0250),4))
  print('\nEl valor esperado y la varianza son \n')
  print('E(h) = ',E)
  print('V(h) = ',V)
  print('\nEl estadistico de prueba es \n')
  print('Z = ',Z)
  print('\ny el punto critico es \n')
  print(Z_a)
  print('\nsi Z < Z_a/2\n')
  print('La prueba es',Z<Z_a)
  return

Ejercicio de clase

In [ ]:


N =     [0.43,0.28,0.33,0.27,0.12]
N = N + [0.31,0.42,0.01,0.32,0.45]
N = N + [0.98,0.79,0.99,0.55,0.67]
N = N + [0.74,0.16,0.20,0.12,0.58]

independencia(N)


Los numeros categorizados son 

[[ 0 -1  1 -1 -1]
 [ 1  1 -1  1  1]
 [ 1 -1  1 -1  1]
 [ 1 -1  1 -1  1]]

El numero de corridas es 

h = 14

El valor esperado y la varianza son 

E(h) =  13.0
V(h) =  3.2333333333333334

El estadistico de prueba es 

Z =  0.5561279983200486

y el punto critico es 

1.96

si Z < Z_a/2

La prueba es True
